bhuf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('redovisning/', include('redovisning.urls', namespace='redovisning')),
]

redovisning/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

app_name = 'redovisning'

urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('organizations/add/', login_required(views.AddOrganizationView), name='addorganization'),
    path('organizations/<int:pk>/', login_required(views.EditOrganizationView.as_view()), name='editorganization'),
    path('members/', login_required(views.MemberListView.as_view()), name='memberlist'),
    path('members/add/', login_required(views.AddMemberView.as_view()), name='addmember'),
    path('members/<int:pk>/', login_required(views.EditMemberView.as_view()), name='editmember'),
    path('members/thankyou/', views.ThankYouView.as_view(), name='thankyou'),
    path('boardmembers/add/', login_required(views.AddBoardmemberView.as_view()), name='addboardmember'),
    path('boardmembers/', login_required(views.BoardmemberListView.as_view()), name='boardmemberlist'),
    path('boardmembers/<int:pk>/', login_required(views.EditBoardmemberView.as_view()), name='editboardmember'),
    path('contacts/add/', login_required(views.AddContactView.as_view()), name='addcontact'),
    path('contacts/', login_required(views.ContactListView.as_view()), name='contactlist'),
    path('contacts/<int:pk>/', login_required(views.EditContactView.as_view()), name='editcontact'),
    path('meetings/add/', login_required(views.AddMeetingView.as_view()), name='addmeeting'),
    path('meetings/', login_required(views.MeetingListView.as_view()), name='meetinglist'),
    path('meetings/<int:pk>/', login_required(views.EditMeetingView.as_view()), name='editmeeting'),
    path('attestations/add/', login_required(views.AddAttestationView.as_view()), name='addattestation'),
    path('attestations/', login_required(views.AttestationListView.as_view()), name='attestationlist'),
    path('login/', auth_views.login, {'template_name': 'redovisning/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'redovisning/login.html'}, name='logout'),
]

redovisning/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class Organization(models.Model):
    org_id = models.AutoField(primary_key=True)
    org_name = models.CharField(max_length=200)
    association = models.CharField(max_length=200)
    corporate = models.CharField(max_length=200)
    national_organization = models.CharField(max_length=200)
    no_of_members = models.IntegerField()
    address = models.TextField()
    phone = models.CharField(max_length=64)
    account_no = models.CharField(max_length=64)
    clr_no = models.CharField(max_length=32)
    agree_send_info = models.BooleanField()
    website = models.CharField(max_length=200)
    social_link = models.CharField(max_length=200)

    def __str__(self):
        return self.org_name

class User(AbstractUser):
    org_id = models.ForeignKey(Organization, on_delete=models.CASCADE,null=True)

class Boardmember(models.Model):
    board_member_id = models.AutoField(primary_key=True)
    org_id = models.ForeignKey(Organization, on_delete=models.CASCADE,null=True)
    member_name = models.CharField(max_length=200)
    post = models.CharField(max_length=200)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length=64)
    gender = models.CharField(max_length=16)

    def __str__(self):
        return self.member_name

class Contact(models.Model):
    contact_id = models.AutoField(primary_key=True)
    org_id = models.ForeignKey(Organization, on_delete=models.CASCADE,null=True)
    contact_name = models.CharField(max_length=200)
    contact_type = models.CharField(max_length=200)
    address = models.TextField()
    email = models.EmailField()
    phone = models.CharField(max_length=64)
    city = models.CharField(max_length=200)
    zipcode = models.CharField(max_length=16)

    def __str__(self):
        return self.contact_name

class Meeeting(models.Model):
    meeting_id = models.AutoField(primary_key=True)
    org_id = models.ForeignKey(Organization, on_delete=models.CASCADE,null=True)
    no_of_meetings = models.IntegerField()
    annual_meeting_date = models.DateField()
    #Vi bifogar föreningens/sektionens gällande stadgar
    current_statuses_attached = models.BooleanField()
    #Stadgarna bifogas ej, då dessa ej ändrats av årsmötet
    #(vid ändring måste stadgar bifogas)
    #statutes_not_attached = models.BooleanField()

    #bedriven verksamhet
    activity = models.TextField()
    #Har föreningen/sektionen samarbetar med andra förening/sektioner i sin verksamhet
    collaboration_with_others = models.BooleanField()
    #Har föreningen/sektionens medlemmar deltagit i aktiviteter anordnade av bhuf
    bhuf_activity = models.BooleanField()

    year = models.CharField(max_length=4)

    def __str__(self):
       return str(self.annual_meeting_date)


class Member(models.Model):
    member_id = models.AutoField(primary_key=True)
    org_id = models.ForeignKey(Organization, on_delete=models.CASCADE,null=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    #date_of_birth = models.DateField()
    year_of_birth = models.CharField(max_length=5)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=64)
    address = models.TextField()
    gender = models.CharField(max_length=16)
    city = models.CharField(max_length=200)
    zipcode = models.CharField(max_length=16)
    date_added = models.DateField()

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Attestation(models.Model):
    attest_id = models.AutoField(primary_key=True)
    org_id = models.ForeignKey(Organization, on_delete=models.CASCADE,null=True)
    printed_name = models.CharField(max_length=200)
    date_signed = models.DateField()

    def __str__(self):
        return self.printed_name

redovisning/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView,ListView,DetailView,UpdateView,CreateView
from redovisning.models import Member,Organization,Boardmember,Contact,Meeeting,Attestation
from redovisning.forms import AddOrganizationForm,AddBoardmemberForm,AddContactForm,AddMeetingForm,AddMemberForm,AddAttestationForm
from redovisning.forms import EditMemberForm,EditMeetingForm,EditBoardmemberForm,EditContactForm,EditOrganizationForm
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from datetime import date
from django.db.models import DateTimeField, F




# Create your views here.
class IndexView(TemplateView):
    template_name = 'redovisning/index.html'

    # def get_how_old(self,getttt):
    #     today = date.today()
    #     return Member.objects.filter(org_id=self.request.user.org_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_list'] = Member.objects.filter(org_id=self.request.user.org_id)
        context['man_members'] = Member.objects.all().filter(org_id=self.request.user.org_id).filter(gender='M')
        #context['today'] = self.get_how_old('444')
        context['test'] = Member.objects.filter(org_id=self.request.user.org_id).filter(gender='M').filter(date_of_birth__gt=F(5))
        return context


class MemberListView(ListView):
    model = Member
    context_object_name = 'member_list'
    template_name = 'redovisning/list_members.html'

    def get_queryset(self):
        return Member.objects.filter(org_id=self.request.user.org_id)

class BoardmemberListView(ListView):
    model = Boardmember
    context_object_name = 'boardmember_list'
    template_name = 'redovisning/list_by_boardmember.html'

    def get_queryset(self):
        return Boardmember.objects.filter(org_id=self.request.user.org_id)

class MeetingListView(ListView):
    model = Meeeting
    context_object_name = 'meeting_list'
    template_name = 'redovisning/list_by_meeting.html'

    def get_queryset(self):
        return Meeeting.objects.filter(org_id=self.request.user.org_id)

class ContactListView(ListView):
    model = Contact
    context_object_name = 'contact_list'
    template_name = 'redovisning/list_contacts.html'

    def get_queryset(self):
        return Contact.objects.filter(org_id=self.request.user.org_id)

class AttestationListView(ListView):
    model = Attestation
    context_object_name = 'attestation_list'
    template_name = 'redovisning/list_attestations.html'

    def get_queryset(self):
        return Attestation.objects.filter(org_id=self.request.user.org_id)

class AddMemberView(CreateView):
    model = Member
    form_class = AddMemberForm
    success_url = reverse_lazy('redovisning:memberlist')
    template_name = 'redovisning/add_member.html'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()
        form.instance.org_id = self.request.user.org_id
        return super().form_valid(form)

class ThankYouView(TemplateView):
    template_name = 'redovisning/add_member_thankyou.html'


def AddOrganizationView(request):
    if request.method == "POST":
        form = AddOrganizationForm(request.POST)
        if form.is_valid():
            post = form.save()
            post.save()
            return redirect('redovisning:thankyou')
    else:
        form = AddOrganizationForm()
    return render(request, 'redovisning/add_organization.html', {'form': form})


class AddBoardmemberView(CreateView):
    model = Boardmember
    form_class = AddBoardmemberForm
    success_url = reverse_lazy('redovisning:boardmemberlist')
    template_name = 'redovisning/add_boardmember.html'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()
        form.instance.org_id = self.request.user.org_id
        return super().form_valid(form)


class AddContactView(CreateView):
    model = Contact
    form_class = AddContactForm
    success_url = reverse_lazy('redovisning:contactlist')
    template_name = 'redovisning/add_contact.html'

    def form_valid(self, form):
        form.instance.org_id = self.request.user.org_id
        return super().form_valid(form)


class AddMeetingView(CreateView):
    model = Meeeting
    form_class = AddMeetingForm
    success_url = reverse_lazy('redovisning:meetinglist')
    template_name = 'redovisning/add_meeting.html'

    def form_valid(self, form):
        form.instance.org_id = self.request.user.org_id
        return super().form_valid(form)

class AddAttestationView(CreateView):
    model = Attestation
    form_class = AddAttestationForm
    success_url = reverse_lazy('redovisning:attestationlist')
    template_name = 'redovisning/add_attestation.html'

    def form_valid(self, form):
        form.instance.org_id = self.request.user.org_id
        return super().form_valid(form)

class EditOrganizationView(UpdateView):
    model = Organization
    form_class = EditOrganizationForm
    success_url = '/redovisning/'
    template_name = 'redovisning/edit_organization.html'


class EditMemberView(UpdateView):
    model = Member
    form_class = EditMemberForm
    success_url = "/redovisning/members/"
    template_name = 'redovisning/edit_member.html'


class EditMeetingView(UpdateView):
    model = Meeeting
    form_class = EditMeetingForm
    success_url = '/redovisning/meetings/'
    template_name = 'redovisning/edit_meeting.html'

class EditBoardmemberView(UpdateView):
    model = Boardmember
    form_class = EditBoardmemberForm
    success_url = '/redovisning/boardmembers/'
    template_name = 'redovisning/edit_boardmember.html'

class EditContactView(UpdateView):
    model = Contact
    form_class = EditContactForm
    success_url = '/redovisning/contacts/'
    template_name = 'redovisning/edit_contact.html'

def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        return redirect('redovisning:thankyou')
    else:
        # Return an 'invalid login' error message.
        return redirect('redovisning:thankyou')

def logout(request):
    logout(request)
    return redirect('redovisning:index')

redovisning/templates/redovisning/add_attestation.html
{% extends "redovisning/base_site.html" %}

{% block title %} Redovisning {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Lägg till attest</h3>
      </div>



      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Attest</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">


              <form action="{% url 'redovisning:addattestation' %}" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <input type="submit" value="Attestera" />
              </form>


            </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</div>














            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

redovisning/templates/redovisning/add_contact.html
{% extends "redovisning/base_site.html" %}

{% block title %} Redovisning {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Lägg till kontakt</h3>
      </div>




      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Detaljer</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">


              <form action="{% url 'redovisning:addcontact' %}" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <input type="submit" value="Submit" />
              </form>


            </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</div>














            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

redovisning/templates/redovisning/add_member.html
{% extends "redovisning/base_site.html" %}

{% block title %} Redovisning {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Lägg till medlem</h3>
      </div>




      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Medlemsinfo</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">


              <form action="" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <input type="submit" value="Submit" />
              </form>


              <!-- {% for object in item_list %}
              <tr>
                <th scope="row"><a href="">{{ object.address }}</a></th>
                <td><a href="">{{ object }}</a></td>
                <td><a href="">{{ object.quantity }}</a></td>
                <td><a href="">{{ object.suplement_charges }}</a></td>
              </tr>
              {% endfor %} -->


            </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</div>














            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

redovisning/templates/redovisning/add_member_thankyou.html
{% extends "redovisning/base_site.html" %}

{% block title %} Redovisning {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Lägg till medlem</h3>
      </div>













      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Projekt</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">

              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Projektnamn</th>
                    <th>Er referens</th>
                    <th>Vår referens</th>
                  </tr>
                </thead>
                <tbody>
                  {% for object in member_list %}
                  <tr>
                    <th scope="row"><a href="{% url 'project:projecteditview' object.project_id %}">{{ object.first_name }}</a></th>
                    <td><a href="{% url 'project:projecteditview' object.project_id %}">{{ object.project_name }}</a></td>
                    <td><a href="{% url 'project:projecteditview' object.project_id %}">{{ object.your_ref_person_name }}</a></td>
                    <td><a href="{% url 'project:projecteditview' object.project_id %}">{{ object.our_ref_person_name }}</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>

            </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</div>














            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

redovisning/templates/redovisning/add_organization.html
{% extends "redovisning/base_site.html" %}

{% block title %} Redovisning {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Lägg till medlem</h3>
      </div>













      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Projekt</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">


              <form action="{% url 'redovisning:addorganization' %}" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <input type="submit" value="Submit" />
              </form>


            </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</div>














            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

redovisning/templates/redovisning/base_site.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>BHUF | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom.css" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/custom.js"></script>
    {% endblock body %}
  </body>
</html>

redovisning/templates/redovisning/list_by_boardmember.html
{% extends "redovisning/base_site.html" %}

{% block title %} Redovisning {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Lista styrelsen</h3>
        <h3><a href="{% url 'redovisning:addboardmember'%}" class="btn btn-primary btn-lg btn-block btn-huge">Lägg till förtroendevald</a></h3>
      </div>


      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Lista medlemmar</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">




              <table class="table">
                <thead>
                  <tr>
                    <th>Namn</th>
                    <th>Efternamn</th>
                    <th>Födelsedatum</th>
                    <th>Kön</th>
                  </tr>
                </thead>
                <tbody>
                  {% for object in boardmember_list %}
                  <tr>
                    <th scope="row"><a href="{% url 'redovisning:editboardmember' object.board_member_id %}">{{ object.member_name }}</a></th>
                    <td><a href="{% url 'redovisning:editboardmember' object.board_member_id %}">{{ object.post }}</a></td>
                    <td><a href="{% url 'redovisning:editboardmember' object.board_member_id %}">{{ object.date_of_birth }}</a></td>
                    <td><a href="{% url 'redovisning:editboardmember' object.board_member_id %}">{{ object.gender }}</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>




            </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</div>














            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

redovisning/templates/redovisning/list_by_meeting.html
{% extends "redovisning/base_site.html" %}

{% block title %} Redovisning {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Lista möten</h3>
        <h3><a href="{% url 'redovisning:addmeeting'%}" class="btn btn-primary btn-lg btn-block btn-huge">Redovisa möten för året</a></h3>
      </div>


      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Lista möten</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">




              <table class="table">
                <thead>
                  <tr>
                    <th>Antal möten</th>
                    <th>Årsmöte</th>
                    <th>År</th>
                  </tr>
                </thead>
                <tbody>
                  {% for object in meeting_list %}
                  <tr>
                    <th scope="row"><a href="{% url 'redovisning:editmeeting' object.meeting_id %}">{{ object.no_of_meetings }}</a></th>
                    <td><a href="">{{ object.annual_meeting_date }}</a></td>
                    <td><a href="">{{ object.year }}</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>




            </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</div>














            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

redovisning/templates/redovisning/list_members.html
{% extends "redovisning/base_site.html" %}

{% block title %} Medlemmar {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Lista medlemmar</h3>
        <h3><a href="{% url 'redovisning:addmember'%}" class="btn btn-primary btn-lg btn-block btn-huge">Lägg till medlem</a></h3>
      </div>



      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Lista medlemmar</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">




              <table class="table">
                <thead>
                  <tr>
                    <th>Förnamn</th>
                    <th>Efternamn</th>
                    <th>Födelsedatum</th>
                    <th>Kön</th>
                  </tr>
                </thead>
                <tbody>
                  {% for object in member_list %}
                  <tr>
                    <th scope="row"><a href="{% url 'redovisning:editmember' object.member_id %}">{{ object.first_name }}</a></th>
                    <td><a href="{% url 'redovisning:editmember' object.member_id %}">{{ object.last_name }}</a></td>
                    <td><a href="{% url 'redovisning:editmember' object.member_id %}">{{ object.date_of_birth }}</a></td>
                    <td><a href="{% url 'redovisning:editmember' object.member_id %}">{{ object.gender }}</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>




            </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</div>














            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}