bhuf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('redovisning/', include('redovisning.urls', namespace='redovisning')),
]

redovisning/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

app_name = 'redovisning'

urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('organizations/add/', login_required(views.AddOrganizationView), name='addorganization'),
    path('organizations/<int:pk>/', login_required(views.EditOrganizationView.as_view()), name='editorganization'),
    path('members/', login_required(views.MemberListView.as_view()), name='memberlist'),
    path('members/add/', login_required(views.AddMemberView.as_view()), name='addmember'),
    path('members/<int:pk>/', login_required(views.EditMemberView.as_view()), name='editmember'),
    path('members/thankyou/', views.ThankYouView.as_view(), name='thankyou'),
    path('boardmembers/add/', login_required(views.AddBoardmemberView.as_view()), name='addboardmember'),
    path('boardmembers/', login_required(views.BoardmemberListView.as_view()), name='boardmemberlist'),
    path('boardmembers/<int:pk>/', login_required(views.EditBoardmemberView.as_view()), name='editboardmember'),
    path('contacts/add/', login_required(views.AddContactView.as_view()), name='addcontact'),
    path('contacts/', login_required(views.ContactListView.as_view()), name='contactlist'),
    path('contacts/<int:pk>/', login_required(views.EditContactView.as_view()), name='editcontact'),
    path('meetings/add/', login_required(views.AddMeetingView.as_view()), name='addmeeting'),
    path('meetings/', login_required(views.MeetingListView.as_view()), name='meetinglist'),
    path('meetings/<int:pk>/', login_required(views.EditMeetingView.as_view()), name='editmeeting'),
    path('attestations/add/', login_required(views.AddAttestationView.as_view()), name='addattestation'),
    path('attestations/', login_required(views.AttestationListView.as_view()), name='attestationlist'),
    path('login/', auth_views.login, {'template_name': 'redovisning/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'redovisning/login.html'}, name='logout'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Aveny App</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  </head>


  <body>

    <h1>Tingstad App</h1>
    {% block content %}

    {% endblock %}

  </body>

</html>

templates/footer.html
<div class="pull-right">
  Powered by Ado :)</a>
</div>
<div class="clearfix"></div>

templates/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="/redovisning/" class="site_title"><i class="fa fa-spinner"></i> <span>BHUF attest</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">

    <div class="profile_info">
      <span>Välkommen,</span>
      <h2>{{ user.get_username }}</h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">

      <ul class="nav side-menu">
        <li><a href="/redovisning/organizations/{{ user.org_id_id }}/"><i class="fa fa-laptop"></i> Förening</a></li>
        <li><a href="/redovisning/members/"><i class="fa fa-laptop"></i> Medlemmar</a></li>
        <li><a href="/redovisning/boardmembers/"><i class="fa fa-laptop"></i> Styrelsen</a></li>
        <li><a href="/redovisning/meetings/"><i class="fa fa-laptop"></i> Sammanträden</a></li>
        <li><a href="/redovisning/contacts/"><i class="fa fa-laptop"></i> Kontaktpersoner</a></li>
        <li><a href="/redovisning/attestations/"><i class="fa fa-laptop"></i> Attest</a></li>
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'redovisning:logout' %}">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
  <!-- /menu footer buttons -->
</div>

templates/top_navigation.html
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>


  </nav>
</div>